SELECT *
FROM USER_INFO;

SELECT *
FROM RANK_INFO;

SELECT *
FROM RANK;

DELETE FROM USER_INFO WHERE ID = '찬혁';

DELETE FROM USER_INFO;
DELETE FROM RANK;
DELETE FROM RANK_INFO;

DROP TABLE RANK;

CREATE TABLE RANK_INFO(ID VARCHAR2(20) NOT NULL PRIMARY KEY ,김건휘 NUMBER,김찬혁 NUMBER,박범석 NUMBER,박형찬 NUMBER ,이하연 NUMBER,조원제 NUMBER);

ALTER TABLE USER_INFO ADD want VARCHAR2(1);